---
all:
  children:
    hypervisors:
      hosts:
        pn50:
          ansible_host: 192.168.0.246
          ansible_user: jrickard
          libvirt_pool_path: /var/lib/libvirt/images
    bastion:
      hosts:
        bastion:
          ansible_host: 192.168.127.5
          ansible_user: root
